### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by doosik71** [doosik71/calculator#6]
프로젝스 시작하기 위한 스켈레톤을 작성합니다.

- main() 함수

**Comment by pyongkun** [comment]
찬성입니다.

**Comment by hewlee3** [comment]
기본 설계 구조를 하시죠.

**Comment by pyongkun** [comment]
함수명은 add, sub, multi, div로 하죠.

**Comment by jyoh2k** [comment]
열심히 하겠습니다

**Comment by doosik71** [comment]
사칙연산을 담당하는 각각의 함수를 작성하는 것이 좋겠습니다.
예를 들면 'add(int a, int b)', 'sub(int a, int b)' 등등.
